Create backend with nodejs
nandordudas/build-todo-app pull request #16
Opened 2023-02-12 22:09 UTC by csaba-nagy

### Description

Work in Progress 🚂

### Linked Issues

It closes #8

### Additional context

2023-02-14 16:06 UTC, nandordudas approved these changes

2023-02-14 16:06 UTC, nandordudas commented on packages/api-express/src/database/database.utils.ts
> +  const { PGHOST, PGUSER, PGDATABASE, PGPASSWORD, PGPORT } = process.env
it should be moved outside from functions body

2023-02-14 16:06 UTC, nandordudas commented on packages/api-express/index.ts
> +  const { rows } = await db.query('SELECT * FROM todos')
missing error handler - any of them - and logger

2023-02-14 21:02 UTC, csaba-nagy commented on packages/api-express/index.ts
> +  const { rows } = await db.query('SELECT * FROM todos')
Thanks for your suggestion. It has been moved to the issue #17

2023-02-14 21:10 UTC, csaba-nagy commented on packages/api-express/src/database/database.utils.ts
> +  const { PGHOST, PGUSER, PGDATABASE, PGPASSWORD, PGPORT } = process.env
Indeed, thank you!

2023-02-15 00:05 UTC, nandordudas requested changes

2023-02-15 00:05 UTC, nandordudas commented on packages/api-express/src/repositories/TodoRepository.ts
> +  addTodo: (title: string) => addTodo(title),
using this format is not a sin but try to use 'kiss'

2023-02-19 18:40 UTC, csaba-nagy commented on packages/api-express/src/repositories/TodoRepository.ts
> +const getAllTodos = () => TodoModel.getAllTodos()
It will be solved in the upcoming PR.

2023-02-19 18:40 UTC, csaba-nagy commented on packages/api-express/src/repositories/TodoRepository.ts
> +  addTodo: (title: string) => addTodo(title),
It will be solved in the upcoming PR.

2023-02-20 01:41 UTC, nandordudas requested changes
Wow, this commit contains a bunch of interesting stuff. Good job!

Please don't forget to separate commits. It's not required because the branch will be rebased and commits will be squashed.

No rush and keep going!

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/app.ts
> +import express = require('express')
Why are you using import+require instead of import+from?

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Contracts/Modelable.ts
> +interface Modelable<V, T> {
Very well!

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Contracts/Modelable.ts
> +export default Modelable
Exporting types default from a module is not convenient, not a problem but keep in mind im the future.

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Controllers/BaseController.ts
> +abstract class BaseController<T extends BaseModelType, V extends Payload> {
Love this too!

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Controllers/BaseController.ts
> +abstract class BaseController<T extends BaseModelType, V extends Payload> {
What's cause is to not exists any abstract function inside this class?

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Controllers/TodoController.ts
> +    request: Request,
🥹

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Controllers/TodoController.ts
> +      next(error)
👏

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Controllers/TodoController.ts
> +      return response.status(201).send({
Some inconsistencies on status code.

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Database/Database.ts
> +    return Database.instance
Just a note, the following one-liner is exact same.

```js
return Database.instance ??= new Database()
```

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Database/Database.ts
> +    await this.client?.query('COMMIT')
Optional chain isn't necessary because we have checked it's value above.

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Database/Database.ts
> +    await this.client?.query('COMMIT')
It happens multiple places, please fix these.

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Middleware/error.ts
> +      error: error?.message || error,
Hm, interest.

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Models/BaseModel.ts
> +abstract class BaseModel<T extends BaseModelType, V extends Payload> implements Modelable<BaseModelType, Payload> {
👏

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Repositories/BaseRepository.ts
> +abstract class BaseRepository<T extends BaseModelType, V extends Payload> {
Using an abstract class without any abstract function isn' a sin. But using abstraction is not necessary here.

What's te reason for using this technique?

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Utilities/EnvValidator.ts
> +    const missingOrInvalidVariables = EnvValidator.requiredEnvVariables
🥰

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Utilities/EnvValidator.ts
> +  public static isExists = (envVariable: string) => Boolean(process.env[envVariable]?.trim())
Or just use `exists` or maybe `has`.

2023-02-20 01:41 UTC, nandordudas commented on packages/api-express/src/Utilities/Validator.ts
> +  public isValid = (): boolean => {
Using class getters should be a good approach, just check documentation about that.

2023-02-20 21:13 UTC, nandordudas requested changes

2023-02-22 17:50 UTC, csaba-nagy commented on packages/api-express/app.ts
> +import express = require('express')
I got an error when I tried to import express that way and eslint recommended this method. 
I modified the import statement as you suggested and now it seems to be working well...strange. I will commit the changes soon.

2023-02-22 17:51 UTC, csaba-nagy commented on packages/api-express/src/Contracts/Modelable.ts
> +interface Modelable<V, T> {
Thank you!

2023-02-22 17:54 UTC, csaba-nagy commented on packages/api-express/src/Contracts/Modelable.ts
> +export default Modelable
Okay, thank you for the correction. Next time, I will not use 'export default' for exporting a type.

2023-02-22 17:55 UTC, csaba-nagy commented on packages/api-express/src/Controllers/BaseController.ts
> +abstract class BaseController<T extends BaseModelType, V extends Payload> {
Thanks! 😎

2023-02-22 18:02 UTC, csaba-nagy commented on packages/api-express/src/Controllers/BaseController.ts
> +abstract class BaseController<T extends BaseModelType, V extends Payload> {
Lack of focus...😔
Same as BaseRepository, I just copied these from that and I didn't notice the missing abstract keywords.
The methods in the BaseController and the BaseRepository should be abstract methods of course. I will fix it soon.

2023-02-22 18:03 UTC, csaba-nagy commented on packages/api-express/src/Repositories/BaseRepository.ts
> +abstract class BaseRepository<T extends BaseModelType, V extends Payload> {
Same as BaseController. I will fix these, I forget to put the abstract keywords. These methods should be abstract of course.

2023-02-22 18:04 UTC, csaba-nagy commented on packages/api-express/src/Utilities/EnvValidator.ts
> +  public static isExists = (envVariable: string) => Boolean(process.env[envVariable]?.trim())
Thank you, I will keep in mind.

2023-02-22 18:57 UTC, csaba-nagy commented on packages/api-express/src/Controllers/BaseController.ts
> +abstract class BaseController<T extends BaseModelType, V extends Payload> {
But, it works because we cannot instanciate the abstract class, so we cannot call the methods.
But I agree with you, way better solution to put these methods as abstract.

2023-02-24 13:10 UTC, nandordudas commented on packages/api-express/app.ts
> +import express = require('express')
Don't follow eslint suggestion firstly, try to modify tsconfig.json instead.

2023-02-24 13:11 UTC, nandordudas commented on packages/api-express/src/Controllers/BaseController.ts
> +abstract class BaseController<T extends BaseModelType, V extends Payload> {
🙇‍♂️

2023-02-24 13:12 UTC, nandordudas approved these changes

2023-02-26 20:08 UTC, nandordudas approved these changes

2023-02-27 17:17 UTC, merged